import { relations, sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  index,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

/* ------------------------------------------------------------------ *
 * Conventions (see docs/decisions/ADR-002-persistence-conventions.md)
 *   - ids            UUIDv7, generated by the application
 *   - money          bigint minor units (piastres) + explicit currency
 *   - timestamps     timestamptz, always stored UTC
 *   - tenancy        organization_id on every business table
 * ------------------------------------------------------------------ */

const timestamps = {
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
};

export const organizations = pgTable('organizations', {
  id: uuid('id').primaryKey(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  ...timestamps,
});

export const userStatus = pgEnum('user_status', ['ACTIVE', 'DISABLED']);

export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey(),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id),
    /** Stored lower-cased; the login lookup relies on that normalisation. */
    email: text('email').notNull(),
    name: text('name').notNull(),
    passwordHash: text('password_hash').notNull(),
    status: userStatus('status').notNull().default('ACTIVE'),
    /** Set when an admin issues a password; cleared once the user picks their own. */
    mustChangePassword: boolean('must_change_password').notNull().default(false),
    lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
    ...timestamps,
  },
  (t) => [
    uniqueIndex('users_email_unique').on(t.email),
    index('users_organization_idx').on(t.organizationId),
  ],
);

export const roles = pgTable(
  'roles',
  {
    id: uuid('id').primaryKey(),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id),
    code: text('code').notNull(),
    name: text('name').notNull(),
    ...timestamps,
  },
  (t) => [uniqueIndex('roles_org_code_unique').on(t.organizationId, t.code)],
);

/**
 * Permissions are rows, not enum branches in code. Adding a capability means
 * inserting a row and granting it, never editing a controller.
 */
export const permissions = pgTable('permissions', {
  code: text('code').primaryKey(),
  description: text('description').notNull(),
});

/** Which rows a grant reaches, kept separate from which action it allows. */
export const permissionScope = pgEnum('permission_scope', ['ALL', 'ASSIGNED']);

export const rolePermissions = pgTable(
  'role_permissions',
  {
    roleId: uuid('role_id')
      .notNull()
      .references(() => roles.id, { onDelete: 'cascade' }),
    permissionCode: text('permission_code')
      .notNull()
      .references(() => permissions.code, { onDelete: 'cascade' }),
    scope: permissionScope('scope').notNull().default('ALL'),
  },
  (t) => [primaryKey({ columns: [t.roleId, t.permissionCode] })],
);

export const userRoles = pgTable(
  'user_roles',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    roleId: uuid('role_id')
      .notNull()
      .references(() => roles.id, { onDelete: 'cascade' }),
  },
  (t) => [primaryKey({ columns: [t.userId, t.roleId] })],
);

/**
 * Opaque server-side sessions. Only the SHA-256 of the token is stored, so a
 * database leak does not hand over live sessions.
 */
export const sessions = pgTable(
  'sessions',
  {
    id: uuid('id').primaryKey(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    tokenHash: text('token_hash').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(),
    userAgent: text('user_agent'),
    ipAddress: text('ip_address'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('sessions_token_hash_unique').on(t.tokenHash),
    index('sessions_user_idx').on(t.userId),
  ],
);

export const actorType = pgEnum('actor_type', ['USER', 'SYSTEM', 'INTEGRATION']);

/**
 * Business-readable history: who did what, when, and to which entity.
 * Append-only - never updated, never deleted. Distinct from application logs.
 */
export const auditEvents = pgTable(
  'audit_events',
  {
    id: uuid('id').primaryKey(),
    organizationId: uuid('organization_id').references(() => organizations.id),
    occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
    actorType: actorType('actor_type').notNull(),
    actorUserId: uuid('actor_user_id').references(() => users.id),
    /** Dotted, past-tense and stable, e.g. "auth.login.succeeded". */
    action: text('action').notNull(),
    entityType: text('entity_type'),
    entityId: uuid('entity_id'),
    data: jsonb('data').$type<Record<string, unknown>>(),
    correlationId: text('correlation_id'),
  },
  (t) => [
    index('audit_events_org_occurred_idx').on(t.organizationId, t.occurredAt),
    index('audit_events_entity_idx').on(t.entityType, t.entityId),
  ],
);

export const orderStatus = pgEnum('order_status', [
  'NEW',
  'CONTACTED',
  'CONFIRMED',
  'READY_TO_SHIP',
  'SHIPPED',
  'ON_HOLD',
  'CANCELLED',
]);

export const orderSource = pgEnum('order_source', ['MANUAL', 'EASYORDERS']);

export const orders = pgTable(
  'orders',
  {
    id: uuid('id').primaryKey(),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id),
    /** Human-facing reference, unique within the organization. */
    orderNumber: text('order_number').notNull(),
    source: orderSource('source').notNull(),
    /** The provider's own id. Null for manually created orders. */
    externalId: text('external_id'),
    status: orderStatus('status').notNull().default('NEW'),
    assignedToUserId: uuid('assigned_to_user_id').references(() => users.id),

    /**
     * Customer details are snapshotted onto the order: editing a customer record
     * later must not silently rewrite what was agreed on a past order.
     */
    customerName: text('customer_name').notNull(),
    customerPhone: text('customer_phone').notNull(),
    customerPhoneRaw: text('customer_phone_raw').notNull(),
    customerAddress: text('customer_address'),
    customerGovernorate: text('customer_governorate'),

    itemsTotal: bigint('items_total', { mode: 'number' }).notNull().default(0),
    shippingTotal: bigint('shipping_total', { mode: 'number' }).notNull().default(0),
    discountTotal: bigint('discount_total', { mode: 'number' }).notNull().default(0),
    grandTotal: bigint('grand_total', { mode: 'number' }).notNull().default(0),
    currency: text('currency').notNull().default('EGP'),

    placedAt: timestamp('placed_at', { withTimezone: true }).notNull(),
    createdByUserId: uuid('created_by_user_id').references(() => users.id),
    ...timestamps,
  },
  (t) => [
    uniqueIndex('orders_org_number_unique').on(t.organizationId, t.orderNumber),
    // Idempotency for provider ingestion: one external order maps to one row.
    uniqueIndex('orders_org_source_external_unique')
      .on(t.organizationId, t.source, t.externalId)
      .where(sql`${t.externalId} is not null`),
    index('orders_org_status_idx').on(t.organizationId, t.status),
    index('orders_assigned_idx').on(t.assignedToUserId),
  ],
);

export const usersRelations = relations(users, ({ one, many }) => ({
  organization: one(organizations, {
    fields: [users.organizationId],
    references: [organizations.id],
  }),
  userRoles: many(userRoles),
}));

export const rolesRelations = relations(roles, ({ many }) => ({
  rolePermissions: many(rolePermissions),
  userRoles: many(userRoles),
}));

export const userRolesRelations = relations(userRoles, ({ one }) => ({
  user: one(users, { fields: [userRoles.userId], references: [users.id] }),
  role: one(roles, { fields: [userRoles.roleId], references: [roles.id] }),
}));

export const rolePermissionsRelations = relations(rolePermissions, ({ one }) => ({
  role: one(roles, { fields: [rolePermissions.roleId], references: [roles.id] }),
}));
